# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d50a35b85851850d6ff6b01913ba2e40e29405eddaec38deb9c0c7696fbd0ebf128983f295213760103332b0db7d85bb8055ac294ac85225e525c6f8096a2b84

test:
  secret_key_base: f45fe325aac74c9c56c3d97e4d40a12ecc7c8156e2a9481bb8fdae0cb7574fa3b2eb1fbf2440f377a38580974cafbb72cec2d90ad3ddf1fca58772e115e02236

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
